# parameters and assumptions
tolerance_distance: 10000  # m
to_final_destination_tolerance: 10000  # m
max_length_new_segment: 100000  # m
max_length_road: math.inf  # m
no_road_multiplier: 1.5
build_new_infrastructure: True
H2_ready_infrastructure: True
allow_first_iteration_conversion: False
target_commodity: ['Hydrogen_Gas', 'Hydrogen_Liquid', 'Ammonia', 'Methane_Gas','Methane_Liquid', 'FTF', 'Methanol']
destination_location: [9.993682, 53.551086]  # [Latitude, Longitude]
destination_continent: 'Europe'

# algorithm configuration
use_provided_data: True
use_minimal_example: True
use_low_storage: False  # distances are not precalculated --> lower storage demand but higher memory and time demand
use_low_memory: False  # avoids parallel processing and large matrix implementations --> lower memory demand but higher time demand
number_cores: 1 # 'max'

paths:
   project_folder: 'C:/Users/mt5285/Transportmodell/'
   raw_data: 'raw_data/'
   processed_data: 'processed_data/'
   results: 'results/'
   
filenames:
   location_data: 'start_destination_combinations.xlsx'
   conversion_costs: 'commodities_conversions.xlsx'
   conversion_losses: 'commodities_conversion_efficiencies.xlsx'
   transportation_costs: 'commodities_transportation_with.xlsx'
   gas_pipeline_geodata: 'gas_pipeline_geodata.csv'
   gas_pipeline_graph: 'gas_pipeline_graphs.csv'
   gas_pipeline_graph_object: 'gas_pipeline_graphs_object.csv'
   oil_pipeline_geodata: 'oil_pipeline_geodata.csv'
   oil_pipeline_graph: 'oil_pipeline_graphs.csv'
   oil_pipeline_graph_object: 'oil_pipeline_graphs_objects.csv'
   ports: 'ports_processed.xlsx'
   shipping_distances: 'inner_infrastructure_distances/ports.csv'
   coastlines: 'coastlines.csv'
   minimal_distances: 'minimal_distances.csv'

