# plotting settings
process_results: ['DE_all_ready', 'DE_h2_ready', 'DE_all_not_ready', 'DE_h2_not_ready']  # folder(s) in results/; creates csv file containing all results of respective folders

# plot infrastructure
infrastructure_plot: True  # plots infrastructure

# single result plots; ['results_1', 'results_2']
production_costs_plot: []  # name of csv file(s); creates h2 production costs plot for results in csv
conversion_costs_plot: []  # name of csv file(s); creates conversion costs plot for results in csv
transport_costs_plot: []  # name of csv file(s); creates transport costs plot for results in csv
total_supply_costs_plot: []  # name of csv file(s); creates total_supply costs plot for results in csv
all_costs_plot: []  # name of csv file(s); creates plot for results in csv containing h2 production, conversion, transport and total supply costs
commodity_plot: []  # name of csv file(s); creates starting commodity plot for results in csv
routes_plot: []  # name of csv file(s); creates routes plot for results in csv
full_plot: []  # name of csv file(s); creates 2x2 plot for results in csv (h2 production costs, total supply costs, commodity, and infrastructure plot)

# comparison plots --> 1x2 or 2x2 plots. Nested lists with each list containing up to 4 results (names of csv files); e.g. [['results_1', 'results_2'], ['results_1', 'results_2', 'results_3', 'results_4']]
production_costs_comparison_plot: [[]]  # creates h2 production costs plot for results in csv
conversion_costs_comparison_plot: [[]]  # creates conversion costs plot for results in csv
transport_costs_comparison_plot: [[]]  # creates transport costs plot for results in csv
total_supply_costs_comparison_plot: [[]]  # creates total_supply costs plot for results in csv
commodity_comparison_plot: [[]]  # creates starting commodity plot for results in csv
routes_comparison_plot: [[]]  # creates routes plot for results in csv

# colors, widths, nice names etc.
commodity_colors:
   Hydrogen_Gas: 'lawngreen'
   Hydrogen_Liquid: 'forestgreen'
   Ammonia: 'violet'
   Methane_Gas: 'dodgerblue'
   Methane_Liquid: 'navy'
   Methanol: 'gold'
   DBT: 'maroon'
   MCH: 'darkorchid'
   FTF: 'orangered'
   None: 'black'

nice_name_dictionary:
   Hydrogen_Gas: 'Hydrogen (Gas)'
   Hydrogen_Liquid: 'Hydrogen (Liquid)'
   Ammonia: 'Ammonia'
   Methane_Gas: 'Methane (Gas)'
   Methane_Liquid: 'Methane (Liquid)'
   Methanol: 'Methanol'
   DBT: 'DBT'
   MCH: 'MCH'
   FTF: 'Fischer-Tropsch Crude'
   None: 'No Data'
   Road: 'Road'
   Shipping: 'Ship'
   Pipeline_Gas: 'Gas Pipeline'
   Pipeline_Liquid: 'Oil Pipeline'
   New_Pipeline_Gas: 'New Gas Pipeline'
   New_Pipeline_Liquid: 'New Oil Pipeline'
   global-any_target_h2_ready: 'All-Ready'
   global-any_target_not_h2_ready: 'All-Not-Ready'
   global-h2_target_h2_ready: 'H2-Ready'
   global-h2_target_not_h2_ready: 'H2-Not-Ready'

transport_mean_styles:
   Road: ''
   Shipping: '.'
   Pipeline_Gas: '/'
   New_Pipeline_Gas: '//'
   Pipeline_Liquid: '+'
   New_Pipeline_Liquid: '.'
   None: '/'

transport_mean_line_styles:
   Road: 'dashed'
   Shipping: 'dotted'
   Pipeline: '-'
   Pipeline_Gas: '-'
   New_Pipeline_Gas: '-'
   Pipeline_Liquid: '-'
   New_Pipeline_Liquid: '-'
   None: '/'

line_widths:
   Hydrogen_Gas:
      Road: 0.5
      Pipeline_Gas: 0.5
      New_Pipeline_Gas: 0.5
   Hydrogen_Liquid:
      Road: 1
      Shipping: 1.5
   Ammonia:
      Road: 0.5
      Shipping: 1
   Methane_Gas:
      Pipeline_Gas: 1
      New_Pipeline_Gas: 1
   Methane_Liquid:
      Road: 0.5
      Shipping: 0.5
   Methanol:
      Road: 0.5
      Shipping: 0.5
   DBT:
      Road: 0.5
      Shipping: 1.5
   MCH:
      Road: 0.5
      Shipping: 1.5
   FTF:
      Road: 0.5
      Shipping: 1
      Pipeline_Liquid: 1
      New_Pipeline_Liquid: 1

infrastructure_colors:
   Road: 'r'
   Shipping: 'b'
   Pipeline_Gas: 'g'
   Pipeline_Oil: 'black'